services:
  db:
    image: mysql:8.0
    restart: always
    container_name: cont_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: hamburgueria_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p12345"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./backend
    container_name: cont_api
    ports:
      - "5002:5002"
    env_file:
      - .env
    volumes:
      - ./frontend/assets/burgers:/app/frontend/assets/burgers
      - ./backend:/app 
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: hamburgueria_db
      DB_USER: root        
      DB_PASSWORD: 12345   
      MAIL_USERNAME: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USE_TLS: ${MAIL_USE_TLS}
      MAIL_USE_SSL: ${MAIL_USE_SSL}
volumes:
  mysql_data: 